### ISSUE TITLE
Pressing any key in settings causes React Invariant Violation

### ISSUE THREAD

**Issue by tobimori** [Sxmurai/eval-plugin#2]
![image](https://user-images.githubusercontent.com/29142128/93717917-0616e600-fb79-11ea-8327-4763926c19f7.png)

**Comment by Sxmurai** [comment]
Did you just press backspace in the settings? I want to reproduce it myself, because I feel like I have a fix.

**Comment by tobimori** [comment]
Yep.

**Comment by tobimori** [comment]
Just tested. Happens with every key.

**Comment by Sxmurai** [comment]
Where did you click in the settings? I've been trying but I cannot seem to reproduce your error. Did you just go Settings > Eval Command and then pressed any key?

**Comment by tobimori** [comment]
Exactly.

**Comment by Sxmurai** [comment]
Interesting, I had actually just rewritten the settings shit, I'll have to push later.

**Comment by Sxmurai** [comment]
I've remade the settings menu. The issue should now be fixed. Feel free to reopen if the issue consists.
