### ISSUE TITLE
Remove "need" for auto complete

### ISSUE THREAD

**Issue by tobimori** [Sxmurai/eval-plugin#3]
When typing something which is exactly the same as something written before, except its missing a part at the end, then there is no way to not auto complete and send what you wrote.

![image](https://user-images.githubusercontent.com/29142128/93717955-47a79100-fb79-11ea-9ea0-6d58a769e939.png)

I'm not able to send it without the mistaken "d"s at the end.

**Comment by Sxmurai** [comment]
I almost want to say that's a bug within the autocomplete itself. Because if I did that with the help command, it would probably do the same thing. I am adding a way to turn autocomplete on/off, but I don't want to half-ass it like that

**Comment by Sxmurai** [comment]
I removed the "need" by allowing you to turn off autocomplete completely. I haven't found a solution to that specific problem, but I think this should be a decent patch. Feel free to reopen if you want to suggest anything else.
